[package]
name = "plrustc"
version = "0.1.0"
edition = "2021"
description = "`rustc_driver` wrapper for plrust"

[dependencies]
once_cell = "1.17.0"
# rustc_tools_util = "0.3.0"
# log = "0.4"
# env-logger = "0.10"

# [build-dependencies]
# rustc_tools_util = "0.3.0"

[dev-dependencies]
compiletest_rs = "0.9"

[package.metadata.rust-analyzer]
rustc_private = true

